// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bxnlwqrpaespztmgbvlf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ4bmx3cXJwYWVzcHp0bWdidmxmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NjYzMDcsImV4cCI6MjA2NjQ0MjMwN30.EHMIDVfPoisr9PTh5UhlPE10DAOQ5JCFO_Ejg0sjgTA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);